// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/api/service/navigation/v1/navigation.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto.Api.Service.Navigation.V1 {
  /// <summary>
  /// A NavigationService declares the gRPC contract for a Navigation service
  /// </summary>
  public static partial class NavigationService
  {
    static readonly string __ServiceName = "proto.api.service.navigation.v1.NavigationService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetModeRequest> __Marshaller_proto_api_service_navigation_v1_GetModeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetModeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetModeResponse> __Marshaller_proto_api_service_navigation_v1_GetModeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetModeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.SetModeRequest> __Marshaller_proto_api_service_navigation_v1_SetModeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.SetModeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.SetModeResponse> __Marshaller_proto_api_service_navigation_v1_SetModeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.SetModeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetLocationRequest> __Marshaller_proto_api_service_navigation_v1_GetLocationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetLocationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetLocationResponse> __Marshaller_proto_api_service_navigation_v1_GetLocationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetLocationResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest> __Marshaller_proto_api_service_navigation_v1_GetWaypointsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse> __Marshaller_proto_api_service_navigation_v1_GetWaypointsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.AddWaypointRequest> __Marshaller_proto_api_service_navigation_v1_AddWaypointRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.AddWaypointRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.AddWaypointResponse> __Marshaller_proto_api_service_navigation_v1_AddWaypointResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.AddWaypointResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest> __Marshaller_proto_api_service_navigation_v1_RemoveWaypointRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse> __Marshaller_proto_api_service_navigation_v1_RemoveWaypointResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.GetModeRequest, global::Proto.Api.Service.Navigation.V1.GetModeResponse> __Method_GetMode = new grpc::Method<global::Proto.Api.Service.Navigation.V1.GetModeRequest, global::Proto.Api.Service.Navigation.V1.GetModeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMode",
        __Marshaller_proto_api_service_navigation_v1_GetModeRequest,
        __Marshaller_proto_api_service_navigation_v1_GetModeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.SetModeRequest, global::Proto.Api.Service.Navigation.V1.SetModeResponse> __Method_SetMode = new grpc::Method<global::Proto.Api.Service.Navigation.V1.SetModeRequest, global::Proto.Api.Service.Navigation.V1.SetModeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetMode",
        __Marshaller_proto_api_service_navigation_v1_SetModeRequest,
        __Marshaller_proto_api_service_navigation_v1_SetModeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.GetLocationRequest, global::Proto.Api.Service.Navigation.V1.GetLocationResponse> __Method_GetLocation = new grpc::Method<global::Proto.Api.Service.Navigation.V1.GetLocationRequest, global::Proto.Api.Service.Navigation.V1.GetLocationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLocation",
        __Marshaller_proto_api_service_navigation_v1_GetLocationRequest,
        __Marshaller_proto_api_service_navigation_v1_GetLocationResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest, global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse> __Method_GetWaypoints = new grpc::Method<global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest, global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWaypoints",
        __Marshaller_proto_api_service_navigation_v1_GetWaypointsRequest,
        __Marshaller_proto_api_service_navigation_v1_GetWaypointsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.AddWaypointRequest, global::Proto.Api.Service.Navigation.V1.AddWaypointResponse> __Method_AddWaypoint = new grpc::Method<global::Proto.Api.Service.Navigation.V1.AddWaypointRequest, global::Proto.Api.Service.Navigation.V1.AddWaypointResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddWaypoint",
        __Marshaller_proto_api_service_navigation_v1_AddWaypointRequest,
        __Marshaller_proto_api_service_navigation_v1_AddWaypointResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest, global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse> __Method_RemoveWaypoint = new grpc::Method<global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest, global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveWaypoint",
        __Marshaller_proto_api_service_navigation_v1_RemoveWaypointRequest,
        __Marshaller_proto_api_service_navigation_v1_RemoveWaypointResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.Api.Service.Navigation.V1.NavigationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NavigationService</summary>
    [grpc::BindServiceMethod(typeof(NavigationService), "BindService")]
    public abstract partial class NavigationServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.GetModeResponse> GetMode(global::Proto.Api.Service.Navigation.V1.GetModeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.SetModeResponse> SetMode(global::Proto.Api.Service.Navigation.V1.SetModeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.GetLocationResponse> GetLocation(global::Proto.Api.Service.Navigation.V1.GetLocationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse> GetWaypoints(global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.AddWaypointResponse> AddWaypoint(global::Proto.Api.Service.Navigation.V1.AddWaypointRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse> RemoveWaypoint(global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NavigationService</summary>
    public partial class NavigationServiceClient : grpc::ClientBase<NavigationServiceClient>
    {
      /// <summary>Creates a new client for NavigationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NavigationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NavigationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NavigationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NavigationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NavigationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetModeResponse GetMode(global::Proto.Api.Service.Navigation.V1.GetModeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetModeResponse GetMode(global::Proto.Api.Service.Navigation.V1.GetModeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetModeResponse> GetModeAsync(global::Proto.Api.Service.Navigation.V1.GetModeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetModeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetModeResponse> GetModeAsync(global::Proto.Api.Service.Navigation.V1.GetModeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.SetModeResponse SetMode(global::Proto.Api.Service.Navigation.V1.SetModeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetMode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.SetModeResponse SetMode(global::Proto.Api.Service.Navigation.V1.SetModeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetMode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.SetModeResponse> SetModeAsync(global::Proto.Api.Service.Navigation.V1.SetModeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetModeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.SetModeResponse> SetModeAsync(global::Proto.Api.Service.Navigation.V1.SetModeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetMode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetLocationResponse GetLocation(global::Proto.Api.Service.Navigation.V1.GetLocationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLocation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetLocationResponse GetLocation(global::Proto.Api.Service.Navigation.V1.GetLocationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLocation, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetLocationResponse> GetLocationAsync(global::Proto.Api.Service.Navigation.V1.GetLocationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLocationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetLocationResponse> GetLocationAsync(global::Proto.Api.Service.Navigation.V1.GetLocationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLocation, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse GetWaypoints(global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWaypoints(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse GetWaypoints(global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWaypoints, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse> GetWaypointsAsync(global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWaypointsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse> GetWaypointsAsync(global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWaypoints, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.AddWaypointResponse AddWaypoint(global::Proto.Api.Service.Navigation.V1.AddWaypointRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddWaypoint(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.AddWaypointResponse AddWaypoint(global::Proto.Api.Service.Navigation.V1.AddWaypointRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddWaypoint, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.AddWaypointResponse> AddWaypointAsync(global::Proto.Api.Service.Navigation.V1.AddWaypointRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddWaypointAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.AddWaypointResponse> AddWaypointAsync(global::Proto.Api.Service.Navigation.V1.AddWaypointRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddWaypoint, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse RemoveWaypoint(global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveWaypoint(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse RemoveWaypoint(global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveWaypoint, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse> RemoveWaypointAsync(global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveWaypointAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse> RemoveWaypointAsync(global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveWaypoint, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override NavigationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NavigationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(NavigationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMode, serviceImpl.GetMode)
          .AddMethod(__Method_SetMode, serviceImpl.SetMode)
          .AddMethod(__Method_GetLocation, serviceImpl.GetLocation)
          .AddMethod(__Method_GetWaypoints, serviceImpl.GetWaypoints)
          .AddMethod(__Method_AddWaypoint, serviceImpl.AddWaypoint)
          .AddMethod(__Method_RemoveWaypoint, serviceImpl.RemoveWaypoint).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NavigationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetMode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.GetModeRequest, global::Proto.Api.Service.Navigation.V1.GetModeResponse>(serviceImpl.GetMode));
      serviceBinder.AddMethod(__Method_SetMode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.SetModeRequest, global::Proto.Api.Service.Navigation.V1.SetModeResponse>(serviceImpl.SetMode));
      serviceBinder.AddMethod(__Method_GetLocation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.GetLocationRequest, global::Proto.Api.Service.Navigation.V1.GetLocationResponse>(serviceImpl.GetLocation));
      serviceBinder.AddMethod(__Method_GetWaypoints, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.GetWaypointsRequest, global::Proto.Api.Service.Navigation.V1.GetWaypointsResponse>(serviceImpl.GetWaypoints));
      serviceBinder.AddMethod(__Method_AddWaypoint, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.AddWaypointRequest, global::Proto.Api.Service.Navigation.V1.AddWaypointResponse>(serviceImpl.AddWaypoint));
      serviceBinder.AddMethod(__Method_RemoveWaypoint, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Api.Service.Navigation.V1.RemoveWaypointRequest, global::Proto.Api.Service.Navigation.V1.RemoveWaypointResponse>(serviceImpl.RemoveWaypoint));
    }

  }
}
#endregion
