// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: component/sensor/v1/sensor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Viam.Component.Sensor.V1 {

  /// <summary>Holder for reflection information generated from component/sensor/v1/sensor.proto</summary>
  public static partial class SensorReflection {

    #region Descriptor
    /// <summary>File descriptor for component/sensor/v1/sensor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SensorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBjb21wb25lbnQvc2Vuc29yL3YxL3NlbnNvci5wcm90bxIYdmlhbS5jb21w",
            "b25lbnQuc2Vuc29yLnYxGhZjb21tb24vdjEvY29tbW9uLnByb3RvGhxnb29n",
            "bGUvYXBpL2Fubm90YXRpb25zLnByb3RvMsMDCg1TZW5zb3JTZXJ2aWNlEo0B",
            "CgtHZXRSZWFkaW5ncxIiLnZpYW0uY29tbW9uLnYxLkdldFJlYWRpbmdzUmVx",
            "dWVzdBojLnZpYW0uY29tbW9uLnYxLkdldFJlYWRpbmdzUmVzcG9uc2UiNYLT",
            "5JMCLxItL3ZpYW0vYXBpL3YxL2NvbXBvbmVudC9zZW5zb3Ive25hbWV9L3Jl",
            "YWRpbmdzEokBCglEb0NvbW1hbmQSIC52aWFtLmNvbW1vbi52MS5Eb0NvbW1h",
            "bmRSZXF1ZXN0GiEudmlhbS5jb21tb24udjEuRG9Db21tYW5kUmVzcG9uc2Ui",
            "N4LT5JMCMSIvL3ZpYW0vYXBpL3YxL2NvbXBvbmVudC9zZW5zb3Ive25hbWV9",
            "L2RvX2NvbW1hbmQSlQEKDUdldEdlb21ldHJpZXMSJC52aWFtLmNvbW1vbi52",
            "MS5HZXRHZW9tZXRyaWVzUmVxdWVzdBolLnZpYW0uY29tbW9uLnYxLkdldEdl",
            "b21ldHJpZXNSZXNwb25zZSI3gtPkkwIxEi8vdmlhbS9hcGkvdjEvY29tcG9u",
            "ZW50L3NlbnNvci97bmFtZX0vZ2VvbWV0cmllc0JDChxjb20udmlhbS5jb21w",
            "b25lbnQuc2Vuc29yLnYxWiNnby52aWFtLmNvbS9hcGkvY29tcG9uZW50L3Nl",
            "bnNvci92MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Viam.Common.V1.CommonReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
