// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: app/agent/v1/agent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Viam.App.Agent.V1 {

  /// <summary>Holder for reflection information generated from app/agent/v1/agent.proto</summary>
  public static partial class AgentReflection {

    #region Descriptor
    /// <summary>File descriptor for app/agent/v1/agent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhhcHAvYWdlbnQvdjEvYWdlbnQucHJvdG8SEXZpYW0uYXBwLmFnZW50LnYx",
            "Gh5nb29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8aHGdvb2dsZS9wcm90",
            "b2J1Zi9zdHJ1Y3QucHJvdG8i5AIKGERldmljZUFnZW50Q29uZmlnUmVxdWVz",
            "dBIOCgJpZBgBIAEoCVICaWQSOAoJaG9zdF9pbmZvGAIgASgLMhsudmlhbS5h",
            "cHAuYWdlbnQudjEuSG9zdEluZm9SCGhvc3RJbmZvEnUKEnN1YnN5c3RlbV92",
            "ZXJzaW9ucxgDIAMoCzJCLnZpYW0uYXBwLmFnZW50LnYxLkRldmljZUFnZW50",
            "Q29uZmlnUmVxdWVzdC5TdWJzeXN0ZW1WZXJzaW9uc0VudHJ5QgIYAVIRc3Vi",
            "c3lzdGVtVmVyc2lvbnMSQQoMdmVyc2lvbl9pbmZvGAQgASgLMh4udmlhbS5h",
            "cHAuYWdlbnQudjEuVmVyc2lvbkluZm9SC3ZlcnNpb25JbmZvGkQKFlN1YnN5",
            "c3RlbVZlcnNpb25zRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUY",
            "AiABKAlSBXZhbHVlOgI4ASKMBgoZRGV2aWNlQWdlbnRDb25maWdSZXNwb25z",
            "ZRJzChFzdWJzeXN0ZW1fY29uZmlncxgBIAMoCzJCLnZpYW0uYXBwLmFnZW50",
            "LnYxLkRldmljZUFnZW50Q29uZmlnUmVzcG9uc2UuU3Vic3lzdGVtQ29uZmln",
            "c0VudHJ5QgIYAVIQc3Vic3lzdGVtQ29uZmlncxJACg5jaGVja19pbnRlcnZh",
            "bBgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvblINY2hlY2tJbnRl",
            "cnZhbBJJChFhZ2VudF91cGRhdGVfaW5mbxgDIAEoCzIdLnZpYW0uYXBwLmFn",
            "ZW50LnYxLlVwZGF0ZUluZm9SD2FnZW50VXBkYXRlSW5mbxJUChd2aWFtX3Nl",
            "cnZlcl91cGRhdGVfaW5mbxgEIAEoCzIdLnZpYW0uYXBwLmFnZW50LnYxLlVw",
            "ZGF0ZUluZm9SFHZpYW1TZXJ2ZXJVcGRhdGVJbmZvEkQKEWFkdmFuY2VkX3Nl",
            "dHRpbmdzGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdFIQYWR2YW5j",
            "ZWRTZXR0aW5ncxJMChVuZXR3b3JrX2NvbmZpZ3VyYXRpb24YBiABKAsyFy5n",
            "b29nbGUucHJvdG9idWYuU3RydWN0UhRuZXR3b3JrQ29uZmlndXJhdGlvbhJI",
            "ChNhZGRpdGlvbmFsX25ldHdvcmtzGAcgASgLMhcuZ29vZ2xlLnByb3RvYnVm",
            "LlN0cnVjdFISYWRkaXRpb25hbE5ldHdvcmtzEkoKFHN5c3RlbV9jb25maWd1",
            "cmF0aW9uGAggASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdFITc3lzdGVt",
            "Q29uZmlndXJhdGlvbhptChVTdWJzeXN0ZW1Db25maWdzRW50cnkSEAoDa2V5",
            "GAEgASgJUgNrZXkSPgoFdmFsdWUYAiABKAsyKC52aWFtLmFwcC5hZ2VudC52",
            "MS5EZXZpY2VTdWJzeXN0ZW1Db25maWdSBXZhbHVlOgI4ASLTAQoVRGV2aWNl",
            "U3Vic3lzdGVtQ29uZmlnEj4KC3VwZGF0ZV9pbmZvGAEgASgLMh0udmlhbS5h",
            "cHAuYWdlbnQudjEuVXBkYXRlSW5mb1IKdXBkYXRlSW5mbxIYCgdkaXNhYmxl",
            "GAIgASgIUgdkaXNhYmxlEiMKDWZvcmNlX3Jlc3RhcnQYAyABKAhSDGZvcmNl",
            "UmVzdGFydBI3CgphdHRyaWJ1dGVzGAQgASgLMhcuZ29vZ2xlLnByb3RvYnVm",
            "LlN0cnVjdFIKYXR0cmlidXRlczoCGAEivwEKC1ZlcnNpb25JbmZvEiMKDWFn",
            "ZW50X3J1bm5pbmcYASABKAlSDGFnZW50UnVubmluZxInCg9hZ2VudF9pbnN0",
            "YWxsZWQYAiABKAlSDmFnZW50SW5zdGFsbGVkEi4KE3ZpYW1fc2VydmVyX3J1",
            "bm5pbmcYAyABKAlSEXZpYW1TZXJ2ZXJSdW5uaW5nEjIKFXZpYW1fc2VydmVy",
            "X2luc3RhbGxlZBgEIAEoCVITdmlhbVNlcnZlckluc3RhbGxlZCJSCghIb3N0",
            "SW5mbxIaCghwbGF0Zm9ybRgBIAEoCVIIcGxhdGZvcm0SFgoGZGlzdHJvGAIg",
            "ASgJUgZkaXN0cm8SEgoEdGFncxgDIAMoCVIEdGFncyKmAQoKVXBkYXRlSW5m",
            "bxIaCghmaWxlbmFtZRgBIAEoCVIIZmlsZW5hbWUSEAoDdXJsGAIgASgJUgN1",
            "cmwSGAoHdmVyc2lvbhgDIAEoCVIHdmVyc2lvbhIWCgZzaGEyNTYYBCABKAxS",
            "BnNoYTI1NhI4CgZmb3JtYXQYBSABKA4yIC52aWFtLmFwcC5hZ2VudC52MS5Q",
            "YWNrYWdlRm9ybWF0UgZmb3JtYXQqnwEKDVBhY2thZ2VGb3JtYXQSHgoaUEFD",
            "S0FHRV9GT1JNQVRfVU5TUEVDSUZJRUQQABIWChJQQUNLQUdFX0ZPUk1BVF9S",
            "QVcQARIVChFQQUNLQUdFX0ZPUk1BVF9YWhACEh0KGVBBQ0tBR0VfRk9STUFU",
            "X0VYRUNVVEFCTEUQAxIgChxQQUNLQUdFX0ZPUk1BVF9YWl9FWEVDVVRBQkxF",
            "EAQyhAEKEkFnZW50RGV2aWNlU2VydmljZRJuChFEZXZpY2VBZ2VudENvbmZp",
            "ZxIrLnZpYW0uYXBwLmFnZW50LnYxLkRldmljZUFnZW50Q29uZmlnUmVxdWVz",
            "dBosLnZpYW0uYXBwLmFnZW50LnYxLkRldmljZUFnZW50Q29uZmlnUmVzcG9u",
            "c2VCqAEKFWNvbS52aWFtLmFwcC5hZ2VudC52MUIKQWdlbnRQcm90b1ABWhxn",
            "by52aWFtLmNvbS9hcGkvYXBwL2FnZW50L3YxogIDVkFBqgIRVmlhbS5BcHAu",
            "QWdlbnQuVjHKAhFWaWFtXEFwcFxBZ2VudFxWMeICHVZpYW1cQXBwXEFnZW50",
            "XFYxXEdQQk1ldGFkYXRh6gIUVmlhbTo6QXBwOjpBZ2VudDo6VjFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Viam.App.Agent.V1.PackageFormat), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.DeviceAgentConfigRequest), global::Viam.App.Agent.V1.DeviceAgentConfigRequest.Parser, new[]{ "Id", "HostInfo", "SubsystemVersions", "VersionInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.DeviceAgentConfigResponse), global::Viam.App.Agent.V1.DeviceAgentConfigResponse.Parser, new[]{ "SubsystemConfigs", "CheckInterval", "AgentUpdateInfo", "ViamServerUpdateInfo", "AdvancedSettings", "NetworkConfiguration", "AdditionalNetworks", "SystemConfiguration" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.DeviceSubsystemConfig), global::Viam.App.Agent.V1.DeviceSubsystemConfig.Parser, new[]{ "UpdateInfo", "Disable", "ForceRestart", "Attributes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.VersionInfo), global::Viam.App.Agent.V1.VersionInfo.Parser, new[]{ "AgentRunning", "AgentInstalled", "ViamServerRunning", "ViamServerInstalled" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.HostInfo), global::Viam.App.Agent.V1.HostInfo.Parser, new[]{ "Platform", "Distro", "Tags" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Viam.App.Agent.V1.UpdateInfo), global::Viam.App.Agent.V1.UpdateInfo.Parser, new[]{ "Filename", "Url", "Version", "Sha256", "Format" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PackageFormat {
    /// <summary>
    /// unknown/unset (autodetection may be attempted)
    /// </summary>
    [pbr::OriginalName("PACKAGE_FORMAT_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// do nothing
    /// </summary>
    [pbr::OriginalName("PACKAGE_FORMAT_RAW")] Raw = 1,
    /// <summary>
    /// decompress .xz file
    /// </summary>
    [pbr::OriginalName("PACKAGE_FORMAT_XZ")] Xz = 2,
    /// <summary>
    /// set executable permissions
    /// </summary>
    [pbr::OriginalName("PACKAGE_FORMAT_EXECUTABLE")] Executable = 3,
    /// <summary>
    /// decompress and set executable
    /// </summary>
    [pbr::OriginalName("PACKAGE_FORMAT_XZ_EXECUTABLE")] XzExecutable = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Device side
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceAgentConfigRequest : pb::IMessage<DeviceAgentConfigRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceAgentConfigRequest> _parser = new pb::MessageParser<DeviceAgentConfigRequest>(() => new DeviceAgentConfigRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceAgentConfigRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigRequest(DeviceAgentConfigRequest other) : this() {
      id_ = other.id_;
      hostInfo_ = other.hostInfo_ != null ? other.hostInfo_.Clone() : null;
      subsystemVersions_ = other.subsystemVersions_.Clone();
      versionInfo_ = other.versionInfo_ != null ? other.versionInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigRequest Clone() {
      return new DeviceAgentConfigRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// robot partID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "host_info" field.</summary>
    public const int HostInfoFieldNumber = 2;
    private global::Viam.App.Agent.V1.HostInfo hostInfo_;
    /// <summary>
    /// info about the host system
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.HostInfo HostInfo {
      get { return hostInfo_; }
      set {
        hostInfo_ = value;
      }
    }

    /// <summary>Field number for the "subsystem_versions" field.</summary>
    public const int SubsystemVersionsFieldNumber = 3;
    private static readonly pbc::MapField<string, string>.Codec _map_subsystemVersions_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 26);
    private readonly pbc::MapField<string, string> subsystemVersions_ = new pbc::MapField<string, string>();
    /// <summary>
    /// current subsystems and versions
    /// DEPRECATED in favor of version_info
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> SubsystemVersions {
      get { return subsystemVersions_; }
    }

    /// <summary>Field number for the "version_info" field.</summary>
    public const int VersionInfoFieldNumber = 4;
    private global::Viam.App.Agent.V1.VersionInfo versionInfo_;
    /// <summary>
    /// Currently installed versions for agent and viam-server
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.VersionInfo VersionInfo {
      get { return versionInfo_; }
      set {
        versionInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceAgentConfigRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceAgentConfigRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(HostInfo, other.HostInfo)) return false;
      if (!SubsystemVersions.Equals(other.SubsystemVersions)) return false;
      if (!object.Equals(VersionInfo, other.VersionInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (hostInfo_ != null) hash ^= HostInfo.GetHashCode();
      hash ^= SubsystemVersions.GetHashCode();
      if (versionInfo_ != null) hash ^= VersionInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (hostInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HostInfo);
      }
      subsystemVersions_.WriteTo(output, _map_subsystemVersions_codec);
      if (versionInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(VersionInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (hostInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HostInfo);
      }
      subsystemVersions_.WriteTo(ref output, _map_subsystemVersions_codec);
      if (versionInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(VersionInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (hostInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HostInfo);
      }
      size += subsystemVersions_.CalculateSize(_map_subsystemVersions_codec);
      if (versionInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VersionInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceAgentConfigRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.hostInfo_ != null) {
        if (hostInfo_ == null) {
          HostInfo = new global::Viam.App.Agent.V1.HostInfo();
        }
        HostInfo.MergeFrom(other.HostInfo);
      }
      subsystemVersions_.MergeFrom(other.subsystemVersions_);
      if (other.versionInfo_ != null) {
        if (versionInfo_ == null) {
          VersionInfo = new global::Viam.App.Agent.V1.VersionInfo();
        }
        VersionInfo.MergeFrom(other.VersionInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (hostInfo_ == null) {
              HostInfo = new global::Viam.App.Agent.V1.HostInfo();
            }
            input.ReadMessage(HostInfo);
            break;
          }
          case 26: {
            subsystemVersions_.AddEntriesFrom(input, _map_subsystemVersions_codec);
            break;
          }
          case 34: {
            if (versionInfo_ == null) {
              VersionInfo = new global::Viam.App.Agent.V1.VersionInfo();
            }
            input.ReadMessage(VersionInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (hostInfo_ == null) {
              HostInfo = new global::Viam.App.Agent.V1.HostInfo();
            }
            input.ReadMessage(HostInfo);
            break;
          }
          case 26: {
            subsystemVersions_.AddEntriesFrom(ref input, _map_subsystemVersions_codec);
            break;
          }
          case 34: {
            if (versionInfo_ == null) {
              VersionInfo = new global::Viam.App.Agent.V1.VersionInfo();
            }
            input.ReadMessage(VersionInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceAgentConfigResponse : pb::IMessage<DeviceAgentConfigResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceAgentConfigResponse> _parser = new pb::MessageParser<DeviceAgentConfigResponse>(() => new DeviceAgentConfigResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceAgentConfigResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigResponse(DeviceAgentConfigResponse other) : this() {
      subsystemConfigs_ = other.subsystemConfigs_.Clone();
      checkInterval_ = other.checkInterval_ != null ? other.checkInterval_.Clone() : null;
      agentUpdateInfo_ = other.agentUpdateInfo_ != null ? other.agentUpdateInfo_.Clone() : null;
      viamServerUpdateInfo_ = other.viamServerUpdateInfo_ != null ? other.viamServerUpdateInfo_.Clone() : null;
      advancedSettings_ = other.advancedSettings_ != null ? other.advancedSettings_.Clone() : null;
      networkConfiguration_ = other.networkConfiguration_ != null ? other.networkConfiguration_.Clone() : null;
      additionalNetworks_ = other.additionalNetworks_ != null ? other.additionalNetworks_.Clone() : null;
      systemConfiguration_ = other.systemConfiguration_ != null ? other.systemConfiguration_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceAgentConfigResponse Clone() {
      return new DeviceAgentConfigResponse(this);
    }

    /// <summary>Field number for the "subsystem_configs" field.</summary>
    public const int SubsystemConfigsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Viam.App.Agent.V1.DeviceSubsystemConfig>.Codec _map_subsystemConfigs_codec
        = new pbc::MapField<string, global::Viam.App.Agent.V1.DeviceSubsystemConfig>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Viam.App.Agent.V1.DeviceSubsystemConfig.Parser), 10);
    private readonly pbc::MapField<string, global::Viam.App.Agent.V1.DeviceSubsystemConfig> subsystemConfigs_ = new pbc::MapField<string, global::Viam.App.Agent.V1.DeviceSubsystemConfig>();
    /// <summary>
    /// subsystems to be installed/configured/updated
    /// note: previously installed subsystems will be removed from the system if removed from this list
    /// DEPRECATED in favor of indidivual update_info and settings fields
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Viam.App.Agent.V1.DeviceSubsystemConfig> SubsystemConfigs {
      get { return subsystemConfigs_; }
    }

    /// <summary>Field number for the "check_interval" field.</summary>
    public const int CheckIntervalFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Duration checkInterval_;
    /// <summary>
    /// how often this request should be repeated
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration CheckInterval {
      get { return checkInterval_; }
      set {
        checkInterval_ = value;
      }
    }

    /// <summary>Field number for the "agent_update_info" field.</summary>
    public const int AgentUpdateInfoFieldNumber = 3;
    private global::Viam.App.Agent.V1.UpdateInfo agentUpdateInfo_;
    /// <summary>
    /// update info for agent and viam-server, parsed/processed in App
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.UpdateInfo AgentUpdateInfo {
      get { return agentUpdateInfo_; }
      set {
        agentUpdateInfo_ = value;
      }
    }

    /// <summary>Field number for the "viam_server_update_info" field.</summary>
    public const int ViamServerUpdateInfoFieldNumber = 4;
    private global::Viam.App.Agent.V1.UpdateInfo viamServerUpdateInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.UpdateInfo ViamServerUpdateInfo {
      get { return viamServerUpdateInfo_; }
      set {
        viamServerUpdateInfo_ = value;
      }
    }

    /// <summary>Field number for the "advanced_settings" field.</summary>
    public const int AdvancedSettingsFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Struct advancedSettings_;
    /// <summary>
    /// various settings that are passed directly to device Agent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct AdvancedSettings {
      get { return advancedSettings_; }
      set {
        advancedSettings_ = value;
      }
    }

    /// <summary>Field number for the "network_configuration" field.</summary>
    public const int NetworkConfigurationFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Struct networkConfiguration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct NetworkConfiguration {
      get { return networkConfiguration_; }
      set {
        networkConfiguration_ = value;
      }
    }

    /// <summary>Field number for the "additional_networks" field.</summary>
    public const int AdditionalNetworksFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Struct additionalNetworks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct AdditionalNetworks {
      get { return additionalNetworks_; }
      set {
        additionalNetworks_ = value;
      }
    }

    /// <summary>Field number for the "system_configuration" field.</summary>
    public const int SystemConfigurationFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Struct systemConfiguration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct SystemConfiguration {
      get { return systemConfiguration_; }
      set {
        systemConfiguration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceAgentConfigResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceAgentConfigResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SubsystemConfigs.Equals(other.SubsystemConfigs)) return false;
      if (!object.Equals(CheckInterval, other.CheckInterval)) return false;
      if (!object.Equals(AgentUpdateInfo, other.AgentUpdateInfo)) return false;
      if (!object.Equals(ViamServerUpdateInfo, other.ViamServerUpdateInfo)) return false;
      if (!object.Equals(AdvancedSettings, other.AdvancedSettings)) return false;
      if (!object.Equals(NetworkConfiguration, other.NetworkConfiguration)) return false;
      if (!object.Equals(AdditionalNetworks, other.AdditionalNetworks)) return false;
      if (!object.Equals(SystemConfiguration, other.SystemConfiguration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SubsystemConfigs.GetHashCode();
      if (checkInterval_ != null) hash ^= CheckInterval.GetHashCode();
      if (agentUpdateInfo_ != null) hash ^= AgentUpdateInfo.GetHashCode();
      if (viamServerUpdateInfo_ != null) hash ^= ViamServerUpdateInfo.GetHashCode();
      if (advancedSettings_ != null) hash ^= AdvancedSettings.GetHashCode();
      if (networkConfiguration_ != null) hash ^= NetworkConfiguration.GetHashCode();
      if (additionalNetworks_ != null) hash ^= AdditionalNetworks.GetHashCode();
      if (systemConfiguration_ != null) hash ^= SystemConfiguration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      subsystemConfigs_.WriteTo(output, _map_subsystemConfigs_codec);
      if (checkInterval_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CheckInterval);
      }
      if (agentUpdateInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AgentUpdateInfo);
      }
      if (viamServerUpdateInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ViamServerUpdateInfo);
      }
      if (advancedSettings_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(AdvancedSettings);
      }
      if (networkConfiguration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NetworkConfiguration);
      }
      if (additionalNetworks_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(AdditionalNetworks);
      }
      if (systemConfiguration_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SystemConfiguration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      subsystemConfigs_.WriteTo(ref output, _map_subsystemConfigs_codec);
      if (checkInterval_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CheckInterval);
      }
      if (agentUpdateInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AgentUpdateInfo);
      }
      if (viamServerUpdateInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ViamServerUpdateInfo);
      }
      if (advancedSettings_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(AdvancedSettings);
      }
      if (networkConfiguration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NetworkConfiguration);
      }
      if (additionalNetworks_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(AdditionalNetworks);
      }
      if (systemConfiguration_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SystemConfiguration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += subsystemConfigs_.CalculateSize(_map_subsystemConfigs_codec);
      if (checkInterval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CheckInterval);
      }
      if (agentUpdateInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgentUpdateInfo);
      }
      if (viamServerUpdateInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ViamServerUpdateInfo);
      }
      if (advancedSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AdvancedSettings);
      }
      if (networkConfiguration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetworkConfiguration);
      }
      if (additionalNetworks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AdditionalNetworks);
      }
      if (systemConfiguration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SystemConfiguration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceAgentConfigResponse other) {
      if (other == null) {
        return;
      }
      subsystemConfigs_.MergeFrom(other.subsystemConfigs_);
      if (other.checkInterval_ != null) {
        if (checkInterval_ == null) {
          CheckInterval = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        CheckInterval.MergeFrom(other.CheckInterval);
      }
      if (other.agentUpdateInfo_ != null) {
        if (agentUpdateInfo_ == null) {
          AgentUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
        }
        AgentUpdateInfo.MergeFrom(other.AgentUpdateInfo);
      }
      if (other.viamServerUpdateInfo_ != null) {
        if (viamServerUpdateInfo_ == null) {
          ViamServerUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
        }
        ViamServerUpdateInfo.MergeFrom(other.ViamServerUpdateInfo);
      }
      if (other.advancedSettings_ != null) {
        if (advancedSettings_ == null) {
          AdvancedSettings = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        AdvancedSettings.MergeFrom(other.AdvancedSettings);
      }
      if (other.networkConfiguration_ != null) {
        if (networkConfiguration_ == null) {
          NetworkConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        NetworkConfiguration.MergeFrom(other.NetworkConfiguration);
      }
      if (other.additionalNetworks_ != null) {
        if (additionalNetworks_ == null) {
          AdditionalNetworks = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        AdditionalNetworks.MergeFrom(other.AdditionalNetworks);
      }
      if (other.systemConfiguration_ != null) {
        if (systemConfiguration_ == null) {
          SystemConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        SystemConfiguration.MergeFrom(other.SystemConfiguration);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            subsystemConfigs_.AddEntriesFrom(input, _map_subsystemConfigs_codec);
            break;
          }
          case 18: {
            if (checkInterval_ == null) {
              CheckInterval = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(CheckInterval);
            break;
          }
          case 26: {
            if (agentUpdateInfo_ == null) {
              AgentUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(AgentUpdateInfo);
            break;
          }
          case 34: {
            if (viamServerUpdateInfo_ == null) {
              ViamServerUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(ViamServerUpdateInfo);
            break;
          }
          case 42: {
            if (advancedSettings_ == null) {
              AdvancedSettings = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(AdvancedSettings);
            break;
          }
          case 50: {
            if (networkConfiguration_ == null) {
              NetworkConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(NetworkConfiguration);
            break;
          }
          case 58: {
            if (additionalNetworks_ == null) {
              AdditionalNetworks = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(AdditionalNetworks);
            break;
          }
          case 66: {
            if (systemConfiguration_ == null) {
              SystemConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(SystemConfiguration);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            subsystemConfigs_.AddEntriesFrom(ref input, _map_subsystemConfigs_codec);
            break;
          }
          case 18: {
            if (checkInterval_ == null) {
              CheckInterval = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(CheckInterval);
            break;
          }
          case 26: {
            if (agentUpdateInfo_ == null) {
              AgentUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(AgentUpdateInfo);
            break;
          }
          case 34: {
            if (viamServerUpdateInfo_ == null) {
              ViamServerUpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(ViamServerUpdateInfo);
            break;
          }
          case 42: {
            if (advancedSettings_ == null) {
              AdvancedSettings = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(AdvancedSettings);
            break;
          }
          case 50: {
            if (networkConfiguration_ == null) {
              NetworkConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(NetworkConfiguration);
            break;
          }
          case 58: {
            if (additionalNetworks_ == null) {
              AdditionalNetworks = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(AdditionalNetworks);
            break;
          }
          case 66: {
            if (systemConfiguration_ == null) {
              SystemConfiguration = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(SystemConfiguration);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DEPRECATED as of January 2025
  /// </summary>
  [global::System.ObsoleteAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceSubsystemConfig : pb::IMessage<DeviceSubsystemConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceSubsystemConfig> _parser = new pb::MessageParser<DeviceSubsystemConfig>(() => new DeviceSubsystemConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceSubsystemConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceSubsystemConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceSubsystemConfig(DeviceSubsystemConfig other) : this() {
      updateInfo_ = other.updateInfo_ != null ? other.updateInfo_.Clone() : null;
      disable_ = other.disable_;
      forceRestart_ = other.forceRestart_;
      attributes_ = other.attributes_ != null ? other.attributes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceSubsystemConfig Clone() {
      return new DeviceSubsystemConfig(this);
    }

    /// <summary>Field number for the "update_info" field.</summary>
    public const int UpdateInfoFieldNumber = 1;
    private global::Viam.App.Agent.V1.UpdateInfo updateInfo_;
    /// <summary>
    /// data needed to download/validate the subsystem
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.UpdateInfo UpdateInfo {
      get { return updateInfo_; }
      set {
        updateInfo_ = value;
      }
    }

    /// <summary>Field number for the "disable" field.</summary>
    public const int DisableFieldNumber = 2;
    private bool disable_;
    /// <summary>
    /// if this subsystem is disabled and should not be started by the agent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Disable {
      get { return disable_; }
      set {
        disable_ = value;
      }
    }

    /// <summary>Field number for the "force_restart" field.</summary>
    public const int ForceRestartFieldNumber = 3;
    private bool forceRestart_;
    /// <summary>
    /// force_restart will restart the subsystem, even if no updates are available
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ForceRestart {
      get { return forceRestart_; }
      set {
        forceRestart_ = value;
      }
    }

    /// <summary>Field number for the "attributes" field.</summary>
    public const int AttributesFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Struct attributes_;
    /// <summary>
    ///arbitrary config sections
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct Attributes {
      get { return attributes_; }
      set {
        attributes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceSubsystemConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceSubsystemConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UpdateInfo, other.UpdateInfo)) return false;
      if (Disable != other.Disable) return false;
      if (ForceRestart != other.ForceRestart) return false;
      if (!object.Equals(Attributes, other.Attributes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (updateInfo_ != null) hash ^= UpdateInfo.GetHashCode();
      if (Disable != false) hash ^= Disable.GetHashCode();
      if (ForceRestart != false) hash ^= ForceRestart.GetHashCode();
      if (attributes_ != null) hash ^= Attributes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (updateInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpdateInfo);
      }
      if (Disable != false) {
        output.WriteRawTag(16);
        output.WriteBool(Disable);
      }
      if (ForceRestart != false) {
        output.WriteRawTag(24);
        output.WriteBool(ForceRestart);
      }
      if (attributes_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Attributes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (updateInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpdateInfo);
      }
      if (Disable != false) {
        output.WriteRawTag(16);
        output.WriteBool(Disable);
      }
      if (ForceRestart != false) {
        output.WriteRawTag(24);
        output.WriteBool(ForceRestart);
      }
      if (attributes_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Attributes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (updateInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateInfo);
      }
      if (Disable != false) {
        size += 1 + 1;
      }
      if (ForceRestart != false) {
        size += 1 + 1;
      }
      if (attributes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Attributes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceSubsystemConfig other) {
      if (other == null) {
        return;
      }
      if (other.updateInfo_ != null) {
        if (updateInfo_ == null) {
          UpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
        }
        UpdateInfo.MergeFrom(other.UpdateInfo);
      }
      if (other.Disable != false) {
        Disable = other.Disable;
      }
      if (other.ForceRestart != false) {
        ForceRestart = other.ForceRestart;
      }
      if (other.attributes_ != null) {
        if (attributes_ == null) {
          Attributes = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Attributes.MergeFrom(other.Attributes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (updateInfo_ == null) {
              UpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(UpdateInfo);
            break;
          }
          case 16: {
            Disable = input.ReadBool();
            break;
          }
          case 24: {
            ForceRestart = input.ReadBool();
            break;
          }
          case 34: {
            if (attributes_ == null) {
              Attributes = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Attributes);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (updateInfo_ == null) {
              UpdateInfo = new global::Viam.App.Agent.V1.UpdateInfo();
            }
            input.ReadMessage(UpdateInfo);
            break;
          }
          case 16: {
            Disable = input.ReadBool();
            break;
          }
          case 24: {
            ForceRestart = input.ReadBool();
            break;
          }
          case 34: {
            if (attributes_ == null) {
              Attributes = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Attributes);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VersionInfo : pb::IMessage<VersionInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VersionInfo> _parser = new pb::MessageParser<VersionInfo>(() => new VersionInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VersionInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VersionInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VersionInfo(VersionInfo other) : this() {
      agentRunning_ = other.agentRunning_;
      agentInstalled_ = other.agentInstalled_;
      viamServerRunning_ = other.viamServerRunning_;
      viamServerInstalled_ = other.viamServerInstalled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VersionInfo Clone() {
      return new VersionInfo(this);
    }

    /// <summary>Field number for the "agent_running" field.</summary>
    public const int AgentRunningFieldNumber = 1;
    private string agentRunning_ = "";
    /// <summary>
    /// the version of agent currently running and making the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AgentRunning {
      get { return agentRunning_; }
      set {
        agentRunning_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "agent_installed" field.</summary>
    public const int AgentInstalledFieldNumber = 2;
    private string agentInstalled_ = "";
    /// <summary>
    /// the version of agent installed (will run after restart if different)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AgentInstalled {
      get { return agentInstalled_; }
      set {
        agentInstalled_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "viam_server_running" field.</summary>
    public const int ViamServerRunningFieldNumber = 3;
    private string viamServerRunning_ = "";
    /// <summary>
    /// the version of viam-server currently running
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ViamServerRunning {
      get { return viamServerRunning_; }
      set {
        viamServerRunning_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "viam_server_installed" field.</summary>
    public const int ViamServerInstalledFieldNumber = 4;
    private string viamServerInstalled_ = "";
    /// <summary>
    /// the version of viam-server installed (will run after restart if different)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ViamServerInstalled {
      get { return viamServerInstalled_; }
      set {
        viamServerInstalled_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VersionInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VersionInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AgentRunning != other.AgentRunning) return false;
      if (AgentInstalled != other.AgentInstalled) return false;
      if (ViamServerRunning != other.ViamServerRunning) return false;
      if (ViamServerInstalled != other.ViamServerInstalled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AgentRunning.Length != 0) hash ^= AgentRunning.GetHashCode();
      if (AgentInstalled.Length != 0) hash ^= AgentInstalled.GetHashCode();
      if (ViamServerRunning.Length != 0) hash ^= ViamServerRunning.GetHashCode();
      if (ViamServerInstalled.Length != 0) hash ^= ViamServerInstalled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AgentRunning.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AgentRunning);
      }
      if (AgentInstalled.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AgentInstalled);
      }
      if (ViamServerRunning.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ViamServerRunning);
      }
      if (ViamServerInstalled.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ViamServerInstalled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AgentRunning.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AgentRunning);
      }
      if (AgentInstalled.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AgentInstalled);
      }
      if (ViamServerRunning.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ViamServerRunning);
      }
      if (ViamServerInstalled.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ViamServerInstalled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AgentRunning.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AgentRunning);
      }
      if (AgentInstalled.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AgentInstalled);
      }
      if (ViamServerRunning.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ViamServerRunning);
      }
      if (ViamServerInstalled.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ViamServerInstalled);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VersionInfo other) {
      if (other == null) {
        return;
      }
      if (other.AgentRunning.Length != 0) {
        AgentRunning = other.AgentRunning;
      }
      if (other.AgentInstalled.Length != 0) {
        AgentInstalled = other.AgentInstalled;
      }
      if (other.ViamServerRunning.Length != 0) {
        ViamServerRunning = other.ViamServerRunning;
      }
      if (other.ViamServerInstalled.Length != 0) {
        ViamServerInstalled = other.ViamServerInstalled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AgentRunning = input.ReadString();
            break;
          }
          case 18: {
            AgentInstalled = input.ReadString();
            break;
          }
          case 26: {
            ViamServerRunning = input.ReadString();
            break;
          }
          case 34: {
            ViamServerInstalled = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AgentRunning = input.ReadString();
            break;
          }
          case 18: {
            AgentInstalled = input.ReadString();
            break;
          }
          case 26: {
            ViamServerRunning = input.ReadString();
            break;
          }
          case 34: {
            ViamServerInstalled = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HostInfo : pb::IMessage<HostInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HostInfo> _parser = new pb::MessageParser<HostInfo>(() => new HostInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HostInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HostInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HostInfo(HostInfo other) : this() {
      platform_ = other.platform_;
      distro_ = other.distro_;
      tags_ = other.tags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HostInfo Clone() {
      return new HostInfo(this);
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 1;
    private string platform_ = "";
    /// <summary>
    /// platform is the docker styled combination of kernel and architecture. Ex: linux/amd64, darwin/arm64
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Platform {
      get { return platform_; }
      set {
        platform_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "distro" field.</summary>
    public const int DistroFieldNumber = 2;
    private string distro_ = "";
    /// <summary>
    /// ID and VERSION_ID fields from /etc/os-release, colon seperated. Ex: ubuntu:22.04, debian:11
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Distro {
      get { return distro_; }
      set {
        distro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// additional tags for specific hardware or software that's present and may affect software selection
    /// ex: "jetson", "rpi4", "systemd", etc.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HostInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HostInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Platform != other.Platform) return false;
      if (Distro != other.Distro) return false;
      if(!tags_.Equals(other.tags_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Platform.Length != 0) hash ^= Platform.GetHashCode();
      if (Distro.Length != 0) hash ^= Distro.GetHashCode();
      hash ^= tags_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Platform.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Platform);
      }
      if (Distro.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Distro);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Platform.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Platform);
      }
      if (Distro.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Distro);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Platform.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Platform);
      }
      if (Distro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Distro);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HostInfo other) {
      if (other == null) {
        return;
      }
      if (other.Platform.Length != 0) {
        Platform = other.Platform;
      }
      if (other.Distro.Length != 0) {
        Distro = other.Distro;
      }
      tags_.Add(other.tags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Platform = input.ReadString();
            break;
          }
          case 18: {
            Distro = input.ReadString();
            break;
          }
          case 26: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Platform = input.ReadString();
            break;
          }
          case 18: {
            Distro = input.ReadString();
            break;
          }
          case 26: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateInfo : pb::IMessage<UpdateInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateInfo> _parser = new pb::MessageParser<UpdateInfo>(() => new UpdateInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Viam.App.Agent.V1.AgentReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateInfo(UpdateInfo other) : this() {
      filename_ = other.filename_;
      url_ = other.url_;
      version_ = other.version_;
      sha256_ = other.sha256_;
      format_ = other.format_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateInfo Clone() {
      return new UpdateInfo(this);
    }

    /// <summary>Field number for the "filename" field.</summary>
    public const int FilenameFieldNumber = 1;
    private string filename_ = "";
    /// <summary>
    /// unpacked filename as it is expected on disk (regardless of url)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Filename {
      get { return filename_; }
      set {
        filename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    /// <summary>
    /// url to download from
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 3;
    private string version_ = "";
    /// <summary>
    /// version expected at the url
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sha256" field.</summary>
    public const int Sha256FieldNumber = 4;
    private pb::ByteString sha256_ = pb::ByteString.Empty;
    /// <summary>
    /// sha256 sum of file as downloaded
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Sha256 {
      get { return sha256_; }
      set {
        sha256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "format" field.</summary>
    public const int FormatFieldNumber = 5;
    private global::Viam.App.Agent.V1.PackageFormat format_ = global::Viam.App.Agent.V1.PackageFormat.Unspecified;
    /// <summary>
    /// determines if decompression or executable permissions are needed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Viam.App.Agent.V1.PackageFormat Format {
      get { return format_; }
      set {
        format_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Filename != other.Filename) return false;
      if (Url != other.Url) return false;
      if (Version != other.Version) return false;
      if (Sha256 != other.Sha256) return false;
      if (Format != other.Format) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Filename.Length != 0) hash ^= Filename.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (Sha256.Length != 0) hash ^= Sha256.GetHashCode();
      if (Format != global::Viam.App.Agent.V1.PackageFormat.Unspecified) hash ^= Format.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Filename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Filename);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Version);
      }
      if (Sha256.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Sha256);
      }
      if (Format != global::Viam.App.Agent.V1.PackageFormat.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Format);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Filename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Filename);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Version);
      }
      if (Sha256.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Sha256);
      }
      if (Format != global::Viam.App.Agent.V1.PackageFormat.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Format);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Filename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filename);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (Sha256.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha256);
      }
      if (Format != global::Viam.App.Agent.V1.PackageFormat.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Format);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateInfo other) {
      if (other == null) {
        return;
      }
      if (other.Filename.Length != 0) {
        Filename = other.Filename;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.Sha256.Length != 0) {
        Sha256 = other.Sha256;
      }
      if (other.Format != global::Viam.App.Agent.V1.PackageFormat.Unspecified) {
        Format = other.Format;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Filename = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 26: {
            Version = input.ReadString();
            break;
          }
          case 34: {
            Sha256 = input.ReadBytes();
            break;
          }
          case 40: {
            Format = (global::Viam.App.Agent.V1.PackageFormat) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Filename = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 26: {
            Version = input.ReadString();
            break;
          }
          case 34: {
            Sha256 = input.ReadBytes();
            break;
          }
          case 40: {
            Format = (global::Viam.App.Agent.V1.PackageFormat) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
